# Assuming that the parameters were optimized before
# CL_CR
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer baseline --dataset mnist --model lenet --tasks CL_CR --lr 0.0025 --p 0.3 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer auto_lambda --dataset mnist --model lenet --tasks CL_CR --lr 0.005 --p 0.3 --lr_relation 0.1 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cagrad --dataset mnist --model lenet --tasks CL_CR --lr 0.0025 --p 0.3 --conv_rate 0.2 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cdtt --dataset mnist --model lenet --tasks CL_CR --lr 0.005 --p 0.2 --alpha 0.6 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer edm --dataset mnist --model lenet --tasks CL_CR --lr 0.005 --p 0.2 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer famo --dataset mnist --model lenet --tasks CL_CR --lr 0.0025 --p 0.2 --gamma 0.001 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer imtl --dataset mnist --model lenet --tasks CL_CR --lr 0.0025 --p 0.3 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer nash --dataset mnist --model lenet --tasks CL_CR --lr 0.0025 --p 0.3 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_rotograd.py --optimizer rotograd --dataset mnist --model lenet --tasks CL_CR --lr 0.005 --p 0.3 --lr_relation 0.1 --feature_size 50 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5

# CL_RR
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer baseline --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer auto_lambda --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --lr_relation 100 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cagrad --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --conv_rate 0.8 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cdtt --dataset mnist --model lenet --tasks CL_RR --lr 0.0025 --p 0.0 --alpha 0.2 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer edm --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer famo --dataset mnist --model lenet --tasks CL_RR --lr 0.0025 --p 0.0 --gamma 0.0001 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer graddrop --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer imtl --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer mgda-ub --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer nash --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer pcgrad --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer rlw-normal --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer rlw-dirichlet --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_rotograd.py --optimizer rotograd --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --lr_relation 0.1 --feature_size 50 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer si --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer uw --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5

# RL_RR
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer baseline --dataset mnist --model lenet --tasks RL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer auto_lambda --dataset mnist --model lenet --tasks RL_RR --lr 0.001 --p 0.0 --lr_relation 100 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cagrad --dataset mnist --model lenet --tasks RL_RR --lr 0.0025 --p 0.0 --conv_rate 0.5 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cdtt --dataset mnist --model lenet --tasks RL_RR --lr 0.001 --p 0.0 --alpha 1.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer edm --dataset mnist --model lenet --tasks RL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer famo --dataset mnist --model lenet --tasks RL_RR --lr 0.001 --p 0.0 --gamma 0.0001 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer imtl --dataset mnist --model lenet --tasks RL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer nash --dataset mnist --model lenet --tasks RL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_rotograd.py --optimizer rotograd --dataset mnist --model lenet --tasks RL_RR --lr 0.001 --p 0.0 --lr_relation 0.1 --feature_size 50 --weight_decay 0 --decay_lr --num_epochs 100 --n_runs 5 --start_index 5