#!/bin/bash
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer baseline --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer auto_lambda --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --lr_relation 100 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cagrad --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --conv_rate 0.8 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cdtt --dataset mnist --model lenet --tasks CL_RR --lr 0.0025 --p 0.0 --alpha 0.2 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer edm --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer famo --dataset mnist --model lenet --tasks CL_RR --lr 0.0025 --p 0.0 --gamma 0.0001 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer graddrop --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer imtl --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer mgda-ub --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer nash --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer pcgrad --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer rlw-normal --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer rlw-dirichlet --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_rotograd.py --optimizer rotograd --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --lr_relation 0.1 --feature_size 50 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer si --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer uw --dataset mnist --model lenet --tasks CL_RR --lr 0.001 --p 0.0 --weight_decay 0 --decay_lr --num_epochs 1 --analysis_test debug

CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer baseline --dataset cityscapes --model resnet18 --shape 512 256 --aug --n_classes 19 --tasks S_D_I --lr 0.001 --p 0.0 --weight_decay 0.0001 --decay_lr --batch_size 32 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer auto_lambda --dataset cityscapes --model resnet18 --shape 512 256 --aug --n_classes 19 --tasks S_D_I --lr 0.001 --p 0.0 --weight_decay 0.0001 --lr_relation 0.0001 --decay_lr --batch_size 32 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cagrad --dataset cityscapes --model resnet18 --shape 512 256 --aug --n_classes 19 --tasks S_D_I --lr 0.001 --p 0.0 --weight_decay 0.0001 --conv_rate 0.2 --decay_lr --batch_size 32 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cdtt --dataset cityscapes --model resnet18 --shape 512 256 --aug --n_classes 19 --tasks S_D_I --lr 0.001 --p 0.0 --weight_decay 0.0001 --alpha 0.2 --decay_lr --batch_size 32 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer edm --dataset cityscapes --model resnet18 --shape 512 256 --aug --n_classes 19 --tasks S_D_I --lr 0.001 --p 0.0 --weight_decay 0.0001 --decay_lr --batch_size 32 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer famo --dataset cityscapes --model resnet18 --shape 512 256 --aug --n_classes 19 --tasks S_D_I --lr 0.001 --p 0.0 --weight_decay 0.0001 --gamma 0.01 --decay_lr --batch_size 32 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer imtl --dataset cityscapes --model resnet18 --shape 512 256 --aug --n_classes 19 --tasks S_D_I --lr 0.001 --p 0.0 --weight_decay 0.0001 --decay_lr --batch_size 32 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer nash --dataset cityscapes --model resnet18 --shape 512 256 --aug --n_classes 19 --tasks S_D_I --lr 0.001 --p 0.0 --weight_decay 0.0001 --decay_lr --batch_size 32 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_rotograd.py --optimizer rotograd --dataset cityscapes --model resnet18 --shape 512 256 --aug --n_classes 19 --tasks S_D_I --lr 0.001 --p 0.0 --weight_decay 0.0 --lr_relation 1.0 --decay_lr --feature_size 512 --post_shape 64 128 --batch_size 32 --num_epochs 1 --analysis_test debug

CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer baseline --dataset QM9 --model mpnn --tasks mu_alpha_homo_lumo_r2_zpve_U0Atom_UAtom_HAtom_GAtom_Cv --lr 0.005 --weight_decay 0 --decay_lr --batch_size 120 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer auto_lambda --dataset QM9 --model mpnn --tasks mu_alpha_homo_lumo_r2_zpve_U0Atom_UAtom_HAtom_GAtom_Cv --lr 0.001 --weight_decay 0 --lr_relation 10 --decay_lr --batch_size 120 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cagrad --dataset QM9 --model mpnn --tasks mu_alpha_homo_lumo_r2_zpve_U0Atom_UAtom_HAtom_GAtom_Cv --lr 0.001 --weight_decay 0 --decay_lr --batch_size 120 --num_epochs 1 --conv_rate 0.8 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer cdtt --dataset QM9 --model mpnn --tasks mu_alpha_homo_lumo_r2_zpve_U0Atom_UAtom_HAtom_GAtom_Cv --lr 0.001 --weight_decay 0 --decay_lr --alpha 1.0 --batch_size 120 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer edm --dataset QM9 --model mpnn --tasks mu_alpha_homo_lumo_r2_zpve_U0Atom_UAtom_HAtom_GAtom_Cv --lr 0.001 --weight_decay 0 --decay_lr --batch_size 120 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer famo --dataset QM9 --model mpnn --tasks mu_alpha_homo_lumo_r2_zpve_U0Atom_UAtom_HAtom_GAtom_Cv --lr 0.005 --weight_decay 0 --decay_lr --gamma 0.0001 --batch_size 120 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer imtl --dataset QM9 --model mpnn --tasks mu_alpha_homo_lumo_r2_zpve_U0Atom_UAtom_HAtom_GAtom_Cv --lr 0.0005 --weight_decay 0 --decay_lr --batch_size 120 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_multi_task.py --optimizer nash --dataset QM9 --model mpnn --tasks mu_alpha_homo_lumo_r2_zpve_U0Atom_UAtom_HAtom_GAtom_Cv --lr 0.001 --weight_decay 0 --decay_lr --batch_size 120 --num_epochs 1 --analysis_test debug
CUDA_VISIBLE_DEVICES=0 python3.8 supervised_experiments/train_rotograd.py --optimizer rotograd --dataset QM9 --model mpnn --tasks mu_alpha_homo_lumo_r2_zpve_U0Atom_UAtom_HAtom_GAtom_Cv --lr 0.001 --lr_relation 0.1 --feature_size 64 --weight_decay 0 --decay_lr --batch_size 120 --num_epochs 1 --analysis_test debug